---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/orders":
    post:
      summary: Creates a new Order
      tags:
      - Orders
      parameters: []
      responses:
        '201':
          description: Order created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                ordered_at:
                  type: string
                  format: date_time
                merchant_id:
                  type: string
              required:
              - amount
              - ordered_at
              - merchant_id
  "/api/v1/reports/disbursement_summary.csv":
    get:
      summary: Get disbursement summary report
      tags:
      - Reports
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    year:
                      type: integer
                      description: The year of the summary
                    disbursements_count:
                      type: integer
                      description: Total number of disbursements in the year
                    total_disbursed:
                      type: number
                      format: float
                      description: Total amount disbursed in the year
                    total_fees:
                      type: number
                      format: float
                      description: Total fees collected in the year
                    monthly_fees_count:
                      type: integer
                      description: Total number of monthly fees in the year
                    monthly_fees_total:
                      type: number
                      format: float
                      description: Total amount of monthly fees in the year
            text/csv:
              schema:
                type: string
                format: binary
                description: CSV file containing the disbursement summary

servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000